### ISSUE TITLE
Questions regarding the paper

### ISSUE THREAD

**Issue by Magauiya** [GuoShi28/2StageAlign#1]
Dear authors,

Thank you for sharing the implementation of your work. It would be nice, if you answer following questions:

1. In section 3.5 Eq. 5, the one-hot loss is designed to make the sum of weights equal to 1 and variance equal to 1/M. However, acc. to Eq. 2, such requirement is already enforced by the softmax. Can you please explain this part?
2. The reconstruction loss in Eq. 8 utilizes function Г(x), which is an ISP post-processing function. Usually such processing performs clamping, rounding, etc. So, how did you make Г(x) differentiable?
3. Have you tried to not initialize the search region with the previous offset estimation? It definitely increases the complexity, but also we can see the "upper-bound" performance of the proposed model.

Best regards

**Comment by GuoShi28** [comment]
1. Using softmax can only normalize the weight to let the sum to be 1. However, if no other constraint is added, the learning process may sometimes learn average weights (e.g., 0.2, 0.2, 0.2, 0.2, 0.2 for K=5), which is not what we want. We want to learn the one-hot vector, which means, only the most match patch from other frames are used to guide the reconstruction of the reference frame.
2.  You can check our code and corresponding papers for more details.  The unprocessing process is approximate into a derivable form.
3. Not initializing the search region is fine. However, it may cause performance degradation when using more frames, since the shift between the reference (r) frame and the distant frame (e.g., r+5 frame) maybe larger than search region.

**Comment by Magauiya** [comment]
Firstly, thank you for your reply! 

1.  Yes, I absolutely agree. That`s why I guess you schedule the temperature of the softmax. I do not see why to add additional constraint.
2. -
3.  What if the search region is limited to the whole image size? In that case, coarse aligner will find better offsets, while initializing with previous offsets may lead to error accumulation.

**Comment by GuoShi28** [comment]
1. We want to obtain the one-hot vector of weight. In some experiments, we find that the learning process may not be very stable without using the constraint. In our final paper, we use the soft to hard strategy to set temperature, which is release this problem. But we also maintain using more constraints for safety.
3. Setting search region to whole image size is very expensive, which is not practical. Yes, if we do not consider the computational cost and running time, I guess searching the most match patch in the whole image is definitely better. 
Also, for the error accumulation, since we perform coarse alignment in patch level for saving computational cost, there much exist some errors. However, since we do not change the structure of image in the coarse alignment period, such error will not accumulate in the refine alignment or coarse alignment for the remaining frames.
